### ISSUE TITLE
probably a typo in the paper

### ISSUE THREAD

**Issue by LucidaLu** [Dhrumil2910/Variational-Quantum-Algorithms-for-Semidefinite-Programming-#1]
Hello, I am a grad student working on VQA, and I find your work quite inspiring!
But there's something confusing me in the paper: on page 11, it reads $X=\lamda\rho, Y=\mu\sigma, \rho,\sigma\in \mathcal{D}^N$, but as far as I can see, $Y$ seems to have the same dimension as $B$, which is $M$, thus $\sigma$ should be accordingly in $\mathcal{D}^M$. Is this true or am I missing something? Many thanks!

**Comment by Dhrumil2910** [comment]
I am glad that you liked our paper. Thanks a lot for pointing out the typo in the paper. As you mentioned, $\sigma$ should be in $\mathcal{D}^M$ instead of $\mathcal{D}^N$.
